### ISSUE TITLE
DigestUtils not exist 

### ISSUE THREAD

**Issue by carloshgomez** [santiaguf/red_social#3]
java: package org.apache.commons.codec.digest does not exist

que opciones tenemos

**Comment by santiaguf** [comment]
@carloshgomez en qué archivo te sale el mensaje? podrías adjuntar una captura de pantalla?

**Comment by santiaguf** [comment]
@carloshgomez puedes descargar el .jar y las dependencies [de este enlace](https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.6/)
